//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GModContentInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GModContentInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;CSS Maps&quot;: {
        ///        &quot;Url&quot;: &quot;https://nextcloud.serpesin.com/s/o2HPLiaKP3om7Ne/download&quot;,
        ///        &quot;InternalName&quot;: &quot;&quot;,
        ///        &quot;DownloadSize&quot;: 59.1,
        ///        &quot;InstallSize&quot;: 234
        ///    },
        ///    &quot;CSS Content&quot;: {
        ///        &quot;Url&quot;: &quot;&quot;,
        ///        &quot;InternalName&quot;: &quot;&quot;,
        ///        &quot;DownloadSize&quot;: 518,
        ///        &quot;InstallSize&quot;: 1280
        ///    },
        ///    &quot;DOD Content&quot;: {
        ///        &quot;Url&quot;: &quot;https://nextcloud.serpensin.com/s/9d6a7GRXakSkSR6/download&quot;,
        ///        &quot;InternalName&quot;: &quot;&quot;,
        ///        &quot;DownloadSize&quot;: 261,
        ///        &quot;InstallSize [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string urls {
            get {
                return ResourceManager.GetString("urls", resourceCulture);
            }
        }
    }
}
